export { AlternatorDynamoDBClient } from "./client-edge.js";
export { routing } from "./routing.js";
export type {
  AlternatorDynamoDBClientApi,
  AlternatorRequestHandler,
} from "./client-edge.js";
export type {
  AlternatorCompressionOptions,
  AlternatorConnectionOptions,
  AlternatorConnectionTimeoutOptions,
  AlternatorDiscoveryOptions,
  AlternatorDynamoDBClientConfig,
  AlternatorEdgeConnectionOptions,
  AlternatorEdgeDynamoDBClientConfig,
  AlternatorHeaderOptimizationOptions,
  AlternatorKeyRouteAffinityConfig,
  AlternatorKeyRouteAffinityMode,
  AlternatorKeyRouteAffinityOptions,
  AlternatorLogger,
  AlternatorNodeConnectionOptions,
  AlternatorNodeDynamoDBClientConfig,
  AlternatorNode,
  AlternatorPartitionKeyByTable,
  AlternatorRequestCompressionConfig,
  AlternatorRequestCompressionOptions,
  AlternatorResponseCompressionAlgorithm,
  AlternatorResponseCompressionConfig,
  AlternatorResponseCompressionOptions,
  AlternatorRuntime,
  AlternatorScheme,
  AlternatorRequestCompressor,
  AlternatorRequestCompressorResult,
  AlternatorTlsOptions,
  AlternatorTlsMaterial,
  AlternatorUserAgentConfig,
  AlternatorUserAgentOptions,
  AlternatorUserAgentTransformer,
  NonEmptyReadonlyArray,
} from "./types.js";
export type {
  AlternatorClusterRoutingScope,
  AlternatorDatacenterRoutingScope,
  AlternatorDatacenterRoutingScopeOptions,
  AlternatorRackRoutingScope,
  AlternatorRackRoutingScopeOptions,
  AlternatorRoutingFallbackOptions,
  AlternatorRoutingScope,
  AlternatorRoutingScopeKind,
} from "./routing.js";
